FROM localhost

MAINTAINER nicasiobernie99@gmail.com

 ENV TERM=xterm\
    TZ=Europe/Berlin\
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt install curl -y


#Installing PHP
RUN apt-get install php -y
RUN apt-get install php-xml -y
RUN apt-get install php-mysql -y
RUN apt-get install php-mbstring -y


#Installing Nginx
RUN apt install nginx -y


#Installing MySlq
RUN apt-get install mysql-server -y


#Installing composer
RUN apt install composer -y


#Installing Yarn
RUN apt-get install gnupg2 -y
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -

RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt update

RUN apt install yarn -y
